// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB_SKKC-dJschmnqrlSq-OCjQWr-bqzHc',
    appId: '1:968622951905:web:a4402a8f93d11459d456a0',
    messagingSenderId: '968622951905',
    projectId: 'beansandbubbles-46ba1',
    authDomain: 'beansandbubbles-46ba1.firebaseapp.com',
    storageBucket: 'beansandbubbles-46ba1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1KSiUtaiaYR0s2tPV3h4kQtvvoKzhd4U',
    appId: '1:968622951905:android:910f2c681c2f1148d456a0',
    messagingSenderId: '968622951905',
    projectId: 'beansandbubbles-46ba1',
    storageBucket: 'beansandbubbles-46ba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMRNGYKX0vx6DT-MqefyIBLqBqaaUPt4k',
    appId: '1:968622951905:ios:4b152c1a9c674380d456a0',
    messagingSenderId: '968622951905',
    projectId: 'beansandbubbles-46ba1',
    storageBucket: 'beansandbubbles-46ba1.appspot.com',
    iosBundleId: 'com.example.productListtt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMRNGYKX0vx6DT-MqefyIBLqBqaaUPt4k',
    appId: '1:968622951905:ios:4b152c1a9c674380d456a0',
    messagingSenderId: '968622951905',
    projectId: 'beansandbubbles-46ba1',
    storageBucket: 'beansandbubbles-46ba1.appspot.com',
    iosBundleId: 'com.example.productListtt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB_SKKC-dJschmnqrlSq-OCjQWr-bqzHc',
    appId: '1:968622951905:web:332db4b03a0eddd6d456a0',
    messagingSenderId: '968622951905',
    projectId: 'beansandbubbles-46ba1',
    authDomain: 'beansandbubbles-46ba1.firebaseapp.com',
    storageBucket: 'beansandbubbles-46ba1.appspot.com',
  );

}